[project]
name = "comfyui-mnemic-nodes"
description = "Updated the version number for the licence requirement"
version = "1.1.2"
license = { file = "LICENSE" }
dependencies = ["configparser", "groq", "transformers", "torch"]

[project.urls]
Repository = "https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "mnemic"
DisplayName = "ComfyUI-mnemic-nodes"
Icon = ""
