[project]
name = "comfyui-mnemic-nodes"
description = "Removed the extension output and renamed the full path output to make it more clear."
version = "1.1.1"
license = { file = "LICENSE" }
dependencies = ["configparser", "groq", "transformers", "torch"]

[project.urls]
Repository = "https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "mnemic"
DisplayName = "ComfyUI-mnemic-nodes"
Icon = ""
