[project]
name = "comfyui-mnemic-nodes"
description = "Added new groq nodes to support vision and audio. Added tooltips to everything. Renamed download image node and removed old groq LLM node."
version = "1.1.3"
license = { file = "LICENSE" }
dependencies = ["configparser", "groq", "transformers", "torch"]

[project.urls]
Repository = "https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "mnemic"
DisplayName = "ComfyUI-mnemic-nodes"
Icon = ""
